project:
  type: website
  output-dir: docs
  
website:
  title: "Food Waste in Singapore"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About Me

format:
  html:
    theme: cosmo
    css: 
      - /css/styles.css
      - /css/bootstrap.css
    page-layout: custom

editor: visual

